// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OzelDers.Data.Concrete.EfCore.Contexts;

#nullable disable

namespace OzelDers.Data.Migrations
{
    [DbContext(typeof(OzelDersContext))]
    partial class OzelDersContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "a9015798-5482-495f-b550-03078d416859",
                            RoleId = "ee25e13f-5eb8-4d39-9310-c92c669a1f4f"
                        },
                        new
                        {
                            UserId = "93107d37-7509-417c-92e4-e5aa42a7a524",
                            RoleId = "6b5fe4a2-5e02-4641-a671-5001260b0419"
                        },
                        new
                        {
                            UserId = "5624bc97-0363-4c5a-b9c8-307308768960",
                            RoleId = "6b5fe4a2-5e02-4641-a671-5001260b0419"
                        },
                        new
                        {
                            UserId = "c88ad64a-8c16-4e26-a062-1511d0af7ab8",
                            RoleId = "6b5fe4a2-5e02-4641-a671-5001260b0419"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OzelDers.Entity.Concrete.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Branchs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Matematik",
                            Url = "matematik"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fizik",
                            Url = "fizik"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Kimya",
                            Url = "kimya"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Tarih",
                            Url = "tarih"
                        },
                        new
                        {
                            Id = 5,
                            Name = "İngilizce",
                            Url = "ingilizce"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Edebiyat",
                            Url = "edebiyat"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Biyoloji",
                            Url = "biyoloji"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Almanca",
                            Url = "almanca"
                        },
                        new
                        {
                            Id = 9,
                            Name = "C#",
                            Url = "c#"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Felsefe",
                            Url = "felsefe"
                        });
                });

            modelBuilder.Entity("OzelDers.Entity.Concrete.Identity.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ee25e13f-5eb8-4d39-9310-c92c669a1f4f",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "6b5fe4a2-5e02-4641-a671-5001260b0419",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "8689f964-57da-4fe3-a0ee-562625e5366c",
                            Name = "Teacher",
                            NormalizedName = "TEACHER"
                        },
                        new
                        {
                            Id = "bc054144-d606-47f8-a543-5b0d4b3a94dc",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        });
                });

            modelBuilder.Entity("OzelDers.Entity.Concrete.Identity.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a9015798-5482-495f-b550-03078d416859",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "63d0913a-9bc6-4dfd-acf2-f2f82a51be0a",
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Deniz",
                            Gender = "Kadın",
                            LastName = "Admin",
                            Location = "İstanbul",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEL4jDVqKV0twaky9czKgobgGOzJ7+NV710qAmBZRRk6HAM59NZS9D55ztCKng4/x1g==",
                            PhoneNumber = "5555555555",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "675b19cb-cadf-46b7-903b-2e3741c9a4aa",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = "93107d37-7509-417c-92e4-e5aa42a7a524",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9f607bf9-2bc9-4fdc-82e8-9283ead32013",
                            Email = "user@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Kemal",
                            Gender = "Erkek",
                            LastName = "User",
                            Location = "Ankara",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@GMAIL.COM",
                            NormalizedUserName = "USER",
                            PasswordHash = "AQAAAAIAAYagAAAAELQvwnz2v32FTEC5HuTgAaLWRS7N0McbV+oh8iwu2sG4HT3v4Y5ZhaUohkxkzqoY/w==",
                            PhoneNumber = "4444444444",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a936c1a3-1e16-4249-8a3d-a3333a6a6369",
                            TwoFactorEnabled = false,
                            UserName = "user"
                        },
                        new
                        {
                            Id = "5624bc97-0363-4c5a-b9c8-307308768960",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3e31efb5-30fe-4c63-958b-624f1c2b9acd",
                            Email = "teacher@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Defne",
                            Gender = "Kadın",
                            LastName = "Teacher",
                            Location = "Ankara",
                            LockoutEnabled = false,
                            NormalizedEmail = "TEACHER@GMAIL.COM",
                            NormalizedUserName = "TEACHER",
                            PasswordHash = "AQAAAAIAAYagAAAAEIGOe+hZebcHkAEWXB/igBqrNViw7HSJrBIcZU0XsUD6bPGxImvGoBDutxwJ14gq/g==",
                            PhoneNumber = "4444444455",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "87db6b2f-164b-427a-aeeb-f64e5bdade65",
                            TwoFactorEnabled = false,
                            UserName = "teacher"
                        },
                        new
                        {
                            Id = "c88ad64a-8c16-4e26-a062-1511d0af7ab8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7a379521-05e9-4d56-a700-5f4c05b3f840",
                            Email = "student@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Yusuf",
                            Gender = "Erkek",
                            LastName = "Student",
                            Location = "Ankara",
                            LockoutEnabled = false,
                            NormalizedEmail = "STUDENT@GMAIL.COM",
                            NormalizedUserName = "STUDENT",
                            PasswordHash = "AQAAAAIAAYagAAAAEBt8XfLqC2K3nvECeDRWqYEv9OKJlVbFf4taxA61cffl/RIQk7YMnr/7HNc+Wc8BlA==",
                            PhoneNumber = "5554444444",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3d860de1-9ee9-417e-ad3d-64ef1f48eada",
                            TwoFactorEnabled = false,
                            UserName = "student"
                        });
                });

            modelBuilder.Entity("OzelDers.Entity.Concrete.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Students", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 17,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lise Öğrencisi",
                            EmailConfirmed = false,
                            FirstName = "Selim",
                            Gender = "erkek",
                            ImageUrl = "1.png",
                            IsDeleted = false,
                            LastName = "Durmuş",
                            Location = "Üsküdar/İstanbul",
                            Url = "selimdurmus"
                        },
                        new
                        {
                            Id = 2,
                            Age = 18,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Üniversite Hazırlık Öğrencisi",
                            EmailConfirmed = false,
                            FirstName = "Defne",
                            Gender = "kız",
                            ImageUrl = "2.png",
                            IsDeleted = false,
                            LastName = "Görmüş",
                            Location = "Çankaya/Ankara",
                            Url = "defnegormus"
                        },
                        new
                        {
                            Id = 3,
                            Age = 21,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Üniversite Öğrencisi",
                            EmailConfirmed = false,
                            FirstName = "Hazal",
                            Gender = "kız",
                            ImageUrl = "3.png",
                            IsDeleted = false,
                            LastName = "Kara",
                            Location = "Çukurova/Adana",
                            Url = "hazalkara"
                        },
                        new
                        {
                            Id = 4,
                            Age = 23,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Üniversite Öğrencisi",
                            EmailConfirmed = false,
                            FirstName = "Gözde",
                            Gender = "kız",
                            ImageUrl = "4.png",
                            IsDeleted = false,
                            LastName = "Çeken",
                            Location = "Bahçelievler/İstanbul",
                            Url = "gozdeceken"
                        },
                        new
                        {
                            Id = 5,
                            Age = 17,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lise Öğrencisi",
                            EmailConfirmed = false,
                            FirstName = "Hüseyin",
                            Gender = "erkek",
                            ImageUrl = "5.png",
                            IsDeleted = false,
                            LastName = "Kazanmış",
                            Location = "Küçükçekmece/İstanbul",
                            Url = "huseyinkazanmıs"
                        },
                        new
                        {
                            Id = 6,
                            Age = 16,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lise Öğrencisi",
                            EmailConfirmed = false,
                            FirstName = "Bilal",
                            Gender = "erkek",
                            ImageUrl = "6.png",
                            IsDeleted = false,
                            LastName = "Telli",
                            Location = "Bornova/İzmir",
                            Url = "bilaltelli"
                        },
                        new
                        {
                            Id = 7,
                            Age = 15,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lise Öğrencisi",
                            EmailConfirmed = false,
                            FirstName = "Yunus",
                            Gender = "erkek",
                            ImageUrl = "7.png",
                            IsDeleted = false,
                            LastName = "Deniz",
                            Location = "İzmit/Kocaeli",
                            Url = "denizyunus"
                        },
                        new
                        {
                            Id = 8,
                            Age = 18,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Üniversite Hazırlık Öğrencisi",
                            EmailConfirmed = false,
                            FirstName = "Cemre",
                            Gender = "kadın",
                            ImageUrl = "8.png",
                            IsDeleted = false,
                            LastName = "Kıran",
                            Location = "Üsküdar/İstanbul",
                            Url = "cemrekıran"
                        },
                        new
                        {
                            Id = 9,
                            Age = 19,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Üniversite Öğrencisi",
                            EmailConfirmed = false,
                            FirstName = "Yusuf",
                            Gender = "erkek",
                            ImageUrl = "9.png",
                            IsDeleted = false,
                            LastName = "Güzel",
                            Location = "Yüreğir/Adana",
                            Url = "yusufguzel"
                        },
                        new
                        {
                            Id = 10,
                            Age = 19,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Üniversite Öğrencisi",
                            EmailConfirmed = false,
                            FirstName = "Harun",
                            Gender = "erkek",
                            ImageUrl = "10.png",
                            IsDeleted = false,
                            LastName = "Bulut",
                            Location = "İskenderun/Hatay",
                            Url = "harunbulut"
                        },
                        new
                        {
                            Id = 11,
                            Age = 20,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Üniversite Öğrencisi",
                            EmailConfirmed = false,
                            FirstName = "Yıldız",
                            Gender = "kız",
                            ImageUrl = "11.png",
                            IsDeleted = false,
                            LastName = "Mutlu",
                            Location = "Pendik/İstanbul",
                            Url = "yıldızmutlu"
                        });
                });

            modelBuilder.Entity("OzelDers.Entity.Concrete.StudentAndTeacher", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.HasKey("StudentId", "TeacherId");

                    b.HasIndex("TeacherId");

                    b.ToTable("StudentAndTeachers");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            TeacherId = 1
                        },
                        new
                        {
                            StudentId = 2,
                            TeacherId = 2
                        },
                        new
                        {
                            StudentId = 3,
                            TeacherId = 2
                        },
                        new
                        {
                            StudentId = 4,
                            TeacherId = 3
                        },
                        new
                        {
                            StudentId = 5,
                            TeacherId = 4
                        },
                        new
                        {
                            StudentId = 6,
                            TeacherId = 5
                        },
                        new
                        {
                            StudentId = 7,
                            TeacherId = 6
                        },
                        new
                        {
                            StudentId = 8,
                            TeacherId = 1
                        },
                        new
                        {
                            StudentId = 9,
                            TeacherId = 3
                        });
                });

            modelBuilder.Entity("OzelDers.Entity.Concrete.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CertifiedTrainer")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<int>("HourlyPrice")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFacetoFace")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UniverstyGraduatedFrom")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Teachers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 27,
                            CertifiedTrainer = true,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Engish lessons are given.",
                            EmailConfirmed = false,
                            FirstName = "Jack",
                            Gender = "erkek",
                            HourlyPrice = 800,
                            ImageUrl = "20.png",
                            IsDeleted = false,
                            IsFacetoFace = false,
                            LastName = "Brand",
                            Location = "Toronto/Canada",
                            UniverstyGraduatedFrom = "Cambridge University",
                            Url = "jackbrand"
                        },
                        new
                        {
                            Id = 2,
                            Age = 27,
                            CertifiedTrainer = true,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fizik dersi verilir.",
                            EmailConfirmed = false,
                            FirstName = "Sevgi",
                            Gender = "kadın",
                            HourlyPrice = 400,
                            ImageUrl = "21.png",
                            IsDeleted = false,
                            IsFacetoFace = true,
                            LastName = "Özer",
                            Location = "Avcılar/İstanbul",
                            UniverstyGraduatedFrom = "İstanbul Üniversitesi",
                            Url = "sevgiozer"
                        },
                        new
                        {
                            Id = 3,
                            Age = 35,
                            CertifiedTrainer = true,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Matematik dersi verilir.",
                            EmailConfirmed = false,
                            FirstName = "Deniz",
                            Gender = "kadın",
                            HourlyPrice = 600,
                            ImageUrl = "22.png",
                            IsDeleted = false,
                            IsFacetoFace = true,
                            LastName = "Kuru",
                            Location = "Avcılar/İstanbul",
                            UniverstyGraduatedFrom = "Fırat Üniversitesi",
                            Url = "denizkuru"
                        },
                        new
                        {
                            Id = 4,
                            Age = 30,
                            CertifiedTrainer = true,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kimya dersi verilir.",
                            EmailConfirmed = false,
                            FirstName = "Fırat",
                            Gender = "erkek",
                            HourlyPrice = 650,
                            ImageUrl = "23.png",
                            IsDeleted = false,
                            IsFacetoFace = true,
                            LastName = "Gören",
                            Location = "Çankaya/Ankara",
                            UniverstyGraduatedFrom = "Marmara Üniversitesi",
                            Url = "fıratgören"
                        },
                        new
                        {
                            Id = 5,
                            Age = 40,
                            CertifiedTrainer = false,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "C# dersi verilir.",
                            EmailConfirmed = false,
                            FirstName = "Kemal",
                            Gender = "erkek",
                            HourlyPrice = 400,
                            ImageUrl = "24.png",
                            IsDeleted = false,
                            IsFacetoFace = true,
                            LastName = "Eren",
                            Location = "Bornova/İzmir",
                            UniverstyGraduatedFrom = "Fırat Üniversitesi",
                            Url = "kemaleren"
                        },
                        new
                        {
                            Id = 6,
                            Age = 25,
                            CertifiedTrainer = true,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Edebiyat dersi verilir.",
                            EmailConfirmed = false,
                            FirstName = "Melis",
                            Gender = "kadın",
                            HourlyPrice = 600,
                            ImageUrl = "25.png",
                            IsDeleted = false,
                            IsFacetoFace = true,
                            LastName = "Susan",
                            Location = "Sefaköy/İstanbul",
                            UniverstyGraduatedFrom = "İstanbul Üniversitesi",
                            Url = "melissusan"
                        },
                        new
                        {
                            Id = 7,
                            Age = 34,
                            CertifiedTrainer = true,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Almanca dersi verilir.",
                            EmailConfirmed = false,
                            FirstName = "Defne",
                            Gender = "kadın",
                            HourlyPrice = 500,
                            ImageUrl = "26.png",
                            IsDeleted = false,
                            IsFacetoFace = false,
                            LastName = "Bilen",
                            Location = "Buca/İzmir",
                            UniverstyGraduatedFrom = "Dokuz Eylül Üniversitesi",
                            Url = "defnebilen"
                        });
                });

            modelBuilder.Entity("OzelDers.Entity.Concrete.TeacherAndBranch", b =>
                {
                    b.Property<int>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BranchId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TeacherId", "BranchId");

                    b.HasIndex("BranchId");

                    b.ToTable("TeacherAndBranches");

                    b.HasData(
                        new
                        {
                            TeacherId = 1,
                            BranchId = 5
                        },
                        new
                        {
                            TeacherId = 2,
                            BranchId = 2
                        },
                        new
                        {
                            TeacherId = 3,
                            BranchId = 1
                        },
                        new
                        {
                            TeacherId = 4,
                            BranchId = 3
                        },
                        new
                        {
                            TeacherId = 5,
                            BranchId = 9
                        },
                        new
                        {
                            TeacherId = 6,
                            BranchId = 6
                        },
                        new
                        {
                            TeacherId = 7,
                            BranchId = 8
                        },
                        new
                        {
                            TeacherId = 7,
                            BranchId = 10
                        },
                        new
                        {
                            TeacherId = 2,
                            BranchId = 8
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("OzelDers.Entity.Concrete.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("OzelDers.Entity.Concrete.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("OzelDers.Entity.Concrete.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("OzelDers.Entity.Concrete.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OzelDers.Entity.Concrete.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("OzelDers.Entity.Concrete.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OzelDers.Entity.Concrete.Student", b =>
                {
                    b.HasOne("OzelDers.Entity.Concrete.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OzelDers.Entity.Concrete.StudentAndTeacher", b =>
                {
                    b.HasOne("OzelDers.Entity.Concrete.Student", "Student")
                        .WithMany("StudentAndTeachers")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OzelDers.Entity.Concrete.Teacher", "Teacher")
                        .WithMany("StudentAndTeachers")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("OzelDers.Entity.Concrete.Teacher", b =>
                {
                    b.HasOne("OzelDers.Entity.Concrete.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OzelDers.Entity.Concrete.TeacherAndBranch", b =>
                {
                    b.HasOne("OzelDers.Entity.Concrete.Branch", "Branch")
                        .WithMany("TeacherAndBranchs")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OzelDers.Entity.Concrete.Teacher", "Teacher")
                        .WithMany("TeacherAndBranches")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("OzelDers.Entity.Concrete.Branch", b =>
                {
                    b.Navigation("TeacherAndBranchs");
                });

            modelBuilder.Entity("OzelDers.Entity.Concrete.Student", b =>
                {
                    b.Navigation("StudentAndTeachers");
                });

            modelBuilder.Entity("OzelDers.Entity.Concrete.Teacher", b =>
                {
                    b.Navigation("StudentAndTeachers");

                    b.Navigation("TeacherAndBranches");
                });
#pragma warning restore 612, 618
        }
    }
}
